# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 969deb5206a7d1e0ba8e1a92646a38685f31bbb387549d36c84e892bae1a1968856c059106714eb915a75f58e3950835906bbeaa6a63008cf80bdad1f669eb75

test:
  secret_key_base: 52917ff874d0f0d25f1d6e6a8db08e834bee3d199e2c0eb24ad1187bbad3c0bf02693380856cfd5a722f1cb2dfeda5fdf08a40126941f08e54b2f806c2bab743

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
